[package]
name = "librec"
version = "0.1.0"
authors = ["HiGuy Smith <higuymb@gmail.com>"]
edition = "2018"

[dependencies]
derive_more = "0.13.0"
nom = "5.0.0"
regex = "1.1.9"
wasm-bindgen = "0.2.47"
cfg-if = "0.1.9"

[lib]
crate-type = ["cdylib", "rlib"]
